name: Repository Dispatch Trigger and Monitor
description: Triggers a workflow and monitors its progress

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  event:
    description: 'Event type to trigger the workflow'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  payload:
    description: 'Client payload content'
    required: false
    default: '{}'
  status_refresh_time:
    description: 'Status refresh interval in seconds'
    required: false
    default: 10

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - run: |
        chmod +x $GITHUB_ACTION_PATH/scripts/workflow.sh
        $GITHUB_ACTION_PATH/scripts/workflow.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EVENT: ${{ inputs.event }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        PAY: ${{ inputs.payload }}
        STATUS_REFRESH_TIME: ${{ inputs.status_refresh_time }}

branding:
  icon: 'fast-forward'
  color: 'gray-dark'
