name: Repository Dispatch Trigger
description: Triggers a workflow and monitors its progress

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  event:
    description: 'Event type to trigger the workflow'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  payload:
    description: 'Payload content'
    required: false
  status_refresh_time:
    description: 'Status update refresh '
    required: false
    default: "10s"

runs:
  using: composite
  steps:
    - run: |
        chmod +x ./workflow.sh
        bash ./workflow.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EVENT: ${{ inputs.event }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        PAY: ${{ inputs.payload }}
        STATUS_REFRESH_TIME: ${{ inputs.status_refresh_time }}
